# Force nixpacks to use Go/Node, not .NET
[providers]
node = "18"
go = "1.18"

[phases.setup]
nixPkgs = ["nodejs-18_x", "go_1_18", "make"]

[phases.install]
cmds = [
  "cd webapp && CPPFLAGS=\"-DPNG_ARM_NEON_OPT=0\" npm install --no-optional",
  "cd webapp && npm run pack"
]

[phases.build]
cmds = [
  "EXCLUDE_PLUGIN=true EXCLUDE_SERVER=true EXCLUDE_ENTERPRISE=true make server-docker os=linux arch=amd64"
]

[start]
cmd = "bin/focalboard-server"

